support openharmony and harmonyos

diff --git a/bin/brew b/bin/brew
--- a/bin/brew
+++ b/bin/brew
@@ -1,16 +1,16 @@
-#!/bin/bash -pu
+#!/bin/zsh -pu
 set -u
 
 # Fail fast with concise message when not using bash
 # Single brackets is needed here for POSIX compatibility
 # shellcheck disable=SC2292
-if [ -z "${BASH_VERSION:-}" ]
+if [[ -z "${ZSH_VERSION:-}" ]]
 then
-  echo "Error: Bash is required to run brew." >&2
+  echo "Error: Zsh is required to run brew." >&2
   exit 1
 fi
 
-set +o posix # as we are using bash now
+#set +o posix # as we are using bash now
 
 # Fail fast with concise messages when PWD has issues
 if [[ -z "${PWD-}" ]]
@@ -49,13 +49,13 @@ symlink_target_directory() {
 }
 
 # Enable and use default Bash builtins rather than user-defined functions
-builtin enable compgen unset
-for cmd in $(builtin compgen -A builtin)
-do
-  builtin unset -f "${cmd}"
-  builtin enable "${cmd}"
-done
-unset cmd
+#builtin enable compgen unset
+#for cmd in $(builtin compgen -A builtin)
+#do
+#  builtin unset -f "${cmd}"
+#  builtin enable "${cmd}"
+#done
+#unset cmd
 
 # Take the HOMEBREW_PATH if we are running brew within brew, otherwise we would lose the original path.
 if [[ -n "${HOMEBREW_BREW_FILE:-}" && -n "${HOMEBREW_PATH:-}" ]]
@@ -184,12 +184,12 @@ MANPAGE_VARS=(
 for VAR in "${MANPAGE_VARS[@]}"
 do
   # Skip if variable value is empty or set to 0.
-  [[ -z "${!VAR:-}" || "${!VAR:-}" = "0" ]] && continue
+  [[ -z "${(P)VAR:-}" || "${(P)VAR:-}" = "0" ]] && continue
 
   VAR_NEW="HOMEBREW_${VAR}"
   # Skip if existing HOMEBREW_* variable is set.
-  [[ -n "${!VAR_NEW:-}" ]] && continue
-  export "${VAR_NEW}"="${!VAR}"
+  [[ -n "${(P)VAR_NEW:-}" ]] && continue
+  export "${VAR_NEW}"="${(P)VAR}"
 done
 
 # We don't want to take the user's value for, e.g., `HOMEBREW_PATH` here!
@@ -213,11 +213,11 @@ USED_BY_HOMEBREW_VARS=(
 for VAR in "${USED_BY_HOMEBREW_VARS[@]}"
 do
   # Skip if variable value is empty.
-  [[ -z "${!VAR:-}" ]] && continue
+  [[ -z "${(P)VAR:-}" ]] && continue
 
   # We unconditionally override `HOMEBREW_*` here.
   VAR_NEW="HOMEBREW_${VAR}"
-  export "${VAR_NEW}"="${!VAR}"
+  export "${VAR_NEW}"="${(P)VAR}"
 done
 
 unset VAR VAR_NEW MANPAGE_VARS USED_BY_HOMEBREW_VARS
@@ -254,7 +254,7 @@ if [[ "${1:-}" == "bundle" ]]
 then
   if [[ "${2:-}" == "exec" || "${2:-}" == "env" || "${2:-}" == "sh" ]]
   then
-    exec /bin/bash -p "${HOMEBREW_LIBRARY}/Homebrew/brew.sh" "$@"
+    exec /bin/zsh -p "${HOMEBREW_LIBRARY}/Homebrew/brew.sh" "$@"
     exit $?
   fi
 fi
@@ -268,12 +268,12 @@ ENV_VAR_NAMES=(
   http_proxy https_proxy ftp_proxy no_proxy all_proxy HTTPS_PROXY FTP_PROXY ALL_PROXY
 )
 # Filter all but the specific variables.
-for VAR in "${ENV_VAR_NAMES[@]}" "${!HOMEBREW_@}"
+for VAR in "${ENV_VAR_NAMES[@]}" ${(k)parameters[(I)HOMEBREW_*]}
 do
   # Skip if variable value is empty.
-  [[ -z "${!VAR:-}" ]] && continue
+  [[ -z "${(P)VAR:-}" ]] && continue
 
-  FILTERED_ENV+=("${VAR}=${!VAR}")
+  FILTERED_ENV+=("${VAR}=${(P)VAR}")
 done
 
 if [[ -n "${CI:-}" ]]
@@ -281,25 +281,25 @@ then
   for VAR in "${!GITHUB_@}"
   do
     # Skip if variable value is empty.
-    [[ -z "${!VAR:-}" ]] && continue
+    [[ -z "${(P)VAR:-}" ]] && continue
     # Skip variables that look like tokens.
     [[ "${VAR}" = *TOKEN* ]] && continue
 
-    FILTERED_ENV+=("${VAR}=${!VAR}")
+    FILTERED_ENV+=("${VAR}=${(P)VAR}")
   done
 fi
 
 if [[ -n "${HOMEBREW_RDBG:-}" ]]
 then
-  for VAR in "${!RUBY_DEBUG_@}"
+for VAR in "${(P)RUBY_DEBUG_@}"
   do
     # Skip if variable value is empty.
-    [[ -z "${!VAR:-}" ]] && continue
+    [[ -z "${(P)VAR:-}" ]] && continue
 
-    FILTERED_ENV+=("${VAR}=${!VAR}")
+    FILTERED_ENV+=("${VAR}=${(P)VAR}")
   done
 fi
 
 unset VAR ENV_VAR_NAMES
 
-exec /usr/bin/env -i "${FILTERED_ENV[@]}" /bin/bash -p "${HOMEBREW_LIBRARY}/Homebrew/brew.sh" "$@"
+exec /usr/bin/env -i "${FILTERED_ENV[@]}" /bin/zsh -p "${HOMEBREW_LIBRARY}/Homebrew/brew.sh" "$@"
